# Generated by Django 4.1.2 on 2022-12-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign',
            new_name='signUp_data',
        ),
    ]
