# Generated by Django 4.1.2 on 2022-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sign_signup_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='addBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(max_length=300, upload_to='images/')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=30)),
                ('disc', models.TextField(max_length=500)),
            ],
        ),
    ]
