# Generated by Django 4.1.2 on 2022-12-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conformation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conformation',
            name='language',
        ),
    ]
