# Generated by Django 4.1.2 on 2022-12-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_conformation_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conformation',
            old_name='passsword',
            new_name='password',
        ),
    ]
