# Generated by Django 4.1.2 on 2022-12-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_returnbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='returnbook',
            new_name='return_book',
        ),
    ]
