# Generated by Django 4.1.2 on 2022-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_conformation_conform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='conform',
            name='id',
        ),
        migrations.RemoveField(
            model_name='return_book',
            name='id',
        ),
        migrations.AlterField(
            model_name='addbook',
            name='book_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conform',
            name='book',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='return_book',
            name='book',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
