# Generated by Django 4.1.2 on 2022-12-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_conform_confirm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='confirm',
            new_name='confirm_book',
        ),
    ]
