# Generated by Django 4.1.2 on 2022-12-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_confirm_confirm_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate_book',
            fields=[
                ('book', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=30)),
                ('disc', models.TextField(max_length=500)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
